Navbar
4GeeksAcademy/PilarGallegoS-exercise-collaborative-html-website pull request #4
Opened 2024-10-30 11:54 UTC by CarmenPG93

Creación del navbar

2024-10-30 13:07 UTC, PilarGallegoS requested changes
Pasar <style> al .css y dejar solo el contenido del <nav>

2024-10-30 17:43 UTC, Daniel-Dudek submitted a review, later dismissed
Perfecto

2024-10-30 18:54 UTC, PilarGallegoS submitted a review, later dismissed
muy bien

2024-11-05 19:24 UTC, closed without merging

2024-11-05 19:24 UTC, PilarGallegoS commented
corrigo en el siguiente PR #9